### ISSUE TITLE
tox -e format installs dependencies and is therefore very slow

### ISSUE THREAD

**Issue by agoscinski** [lab-cosmo/equisolve#16]
Wanted to do formatting that the lint tests are happy and I found the command `tox -e format`, but it installs all dependencies, which makes this take ages (1-2 mins). Can this be simplified, because I don't think one needs to install equistore to reformatting.

**Comment by agoscinski** [comment]
okay the dependencies just need to be installed one time, I thought it creates a new environment each time. So its not really an issue I guess and can be closed.

**Comment by agoscinski** [comment]
I changed my mind, it makes sense to at least check if one can simply skip the installation, but I put a low-prio flag on it, since this only happens once

**Comment by Luthaf** [comment]
the format testenv needs to use `skip_install = true`, like the lint testenv: https://github.com/lab-cosmo/equisolve/blob/258b904746facadee63849428ae93b2c030df6f4/tox.ini#L19
