### ISSUE TITLE
Relative imports for tests

### ISSUE THREAD

**Issue by agoscinski** [lab-cosmo/equisolve#20]
I am adding a utils file to the tests in #15 , but to use it in the other tests, we need relative imports. I am not sure how we will go with this, but I feel that this needs a bit more moving of files so I make this issue to address it in a different PR.

**Comment by Luthaf** [comment]
You can add an empty `__init__.py` file in the tests folder to enable relative imports

**Comment by agoscinski** [comment]
ah okay tried it, but for some reasons it did not work last time. Also very confusing to debug, if we do not add __init__.py in every subdirectory it tries to import numpy.testing from our numpy "module" which does not exist.

**Comment by agoscinski** [comment]
okay we have a problem with some tests in utils folder, because numpy import clashes with numpy subdirectory.

**Comment by PicoCentauri** [comment]
Fixed by #21
