### ISSUE TITLE
Should the unit testing infrastructure be consistent with equistore?

### ISSUE THREAD

**Issue by jwa7** [lab-cosmo/equisolve#23]
Currently equisolve uses `pytest` and equistore `unittest` for unit testing. To make the barrier to entry lower for developers contributing to both projects, in my opinion the same unit testing infrastructure should be used for both. There are of course pros and cons to each, the main advantage of `pytest` being its easy-to-use function parametrisation. As equistore is more established, though perhaps it would be easier to continue with `unittest`. Thoughts?

**Comment by PicoCentauri** [comment]
Thanks for the issue. 

 I would rather move all projects to `pytest`. With `pytest` we could clean up our tests a lot and porting is not so hard.

_It is already in my list for the next dev-meeting._

**Comment by jwa7** [comment]
Ok great, thanks!

**Comment by agoscinski** [comment]
We need to just check if pytest is the best option. Here a list of things we might to check

- [ ] Robot
- [ ] PyTest
- [x] Unittest
- [ ] DocTest
- [ ]  Nose2 (@ceriottm was seemed not to be amazed of it)
- [ ] Testify

Will edit this comment if new packages are suggested

**Comment by Luthaf** [comment]
> PLEASE NOTE: Yelp is in the process of switching to [py.test](http://pytest.org/). We recommend you use it instead of Testify.
-- https://github.com/Yelp/Testify

> [pytest](http://pytest.readthedocs.io/en/latest/) is an excellent test framework and we encourage users to consider it for new projects.
-- https://docs.nose2.io/en/latest/index.html

Sounds like pytest is the way to go everywhere =)
